version: '3'

services:

  postgres:
    image: "postgres:13.1-alpine"
    container_name: "wardrobe-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-wardrobe}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
