version: '3'

services:

  postgres:
    image: "dock.es.ecg.tools/hub.docker.com/postgres:13-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-wardrobe}
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
