version: '3'

services:
  wardrobeApi:
    image: wardrobe-api
    build:
      context: ./target/docker
    expose:
      - 8080
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wardrobe
      - DB_USER=user
      - DB_PASSWORD=1234
      - SERVER_HTTP_PORT=8080

  postgres:
    extends:
      service: postgres
      file: docker-compose.yml
    environment:
      - POSTGRES_DB=wardrobe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
